### ISSUE TITLE
Build fails in Go 1.13.

### ISSUE THREAD

**Issue by berkant** [vcaesar/gops#1]
I'm trying to `go get` robotgo in module-aware set-up with Go 1.13. This error occurs however:

```
$ go list -m -json all
go: finding github.com/shirou/gopsutil v2.19.6+incompatible
go: finding github.com/shirou/gopsutil v2.19.6+incompatible
go list -m: github.com/shirou/gopsutil@v2.19.6+incompatible: invalid version: +incompatible suffix not allowed: module contains a go.mod file, so semantic import versioning is required
```

If I try with `-u` flag in `go get`, it updates the minor to `10`, making it `v2.19.10` which does not have a `go.mod` file, thus it succeeds. Without `-u` fails as above.

My suggestion is that ~`+incompatible` be deleted from go.mod~. Note: Major versions other than 0 and 1 require a distinct import path like `example.com/mod/v<N>`. So +incompatible can't be deleted. Instead the minor version should be updated to `10`.

**Comment by vcaesar** [comment]
Can't reproduce on my device, and `v2.19.10` has serious bugs, just returned `v2.19.6`.

**Comment by berkant** [comment]
gopsutil's versioning seems a bit off. The problem is reproduced if gops is transitively used via gorobot in a module (i.e. `go get github.com/go-vgo/gorobot`). `-u` flag does fix it but updates the minor from `6` to `10`.
